server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/fueling
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

service.kafka.send.order: true
