server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/fueling
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
